"""empty message

Revision ID: cc1779304510
Revises: e20c242b9231
Create Date: 2023-04-05 12:09:37.326251

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc1779304510'
down_revision = 'e20c242b9231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.drop_column('Content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Content', mysql.TEXT(), nullable=False))
        batch_op.drop_column('content')

    # ### end Alembic commands ###
